version: '3.8'

services:
  app-prices-stats-backend:
    build: ./apps/prices-stats/backend
    ports:
      - 3000:3000
    volumes:
      - ./apps/prices-stats/backend:/app/apps/prices-stats/backend
      - ./Contexts:/app/Contexts
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.flowconfig:/app/.flowconfig
      - ./flow-typed:/app/flow-typed
      - ./node_modules:/app/node_modules
