// flow-typed signature: 9d6a293c8e7e1dac38f3fb3e7c552144
// flow-typed version: <<STUB>>/babel-loader_v^8.2.2/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-loader' {
  declare module.exports: any;
}
