// flow-typed signature: d8e0e42e6abc22fa46bfe28bdb6631be
// flow-typed version: <<STUB>>/babel-eslint_v^10.1.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
  declare module.exports: any;
}
