// flow-typed signature: 7cd41a94e19e82bfae5bdbc92f4a0a2c
// flow-typed version: <<STUB>>/babel-preset-es2015_v^6.24.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015' {
  declare module.exports: any;
}
