// flow-typed signature: e5cbd4702b2b98b7a33ec8ba9e6038c9
// flow-typed version: <<STUB>>/copy-webpack-plugin_v^8.1.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-webpack-plugin' {
  declare module.exports: any;
}
