// flow-typed signature: 8ee48cd13baeaccd62ba8f38aba7aa99
// flow-typed version: <<STUB>>/cross-env_v^7.0.3/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-env' {
  declare module.exports: any;
}
