// flow-typed signature: 082fa0ddc4cc7533fc29a8f74b29a650
// flow-typed version: <<STUB>>/eslint-plugin-import_v^2.22.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-import' {
  declare module.exports: any;
}
