// flow-typed signature: 8c608277f066de82d7d386862c766c0d
// flow-typed version: <<STUB>>/eslint_v^7.2.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare module.exports: any;
}
