// flow-typed signature: b7397acec7bd36f917179d3b5e62e263
// flow-typed version: <<STUB>>/eslint-config-airbnb-base_v14.2.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-airbnb-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-airbnb-base' {
  declare module.exports: any;
}
