// flow-typed signature: bdcdc154b047b91db3bfdba8ef0495ca
// flow-typed version: <<STUB>>/express-promise-router_v4.1.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-promise-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-promise-router' {
  import type { Router, RouterOptions } from 'express';

  declare function PromiseRouter(options?: RouterOptions): Router;

  declare export default typeof PromiseRouter;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-promise-router/lib/express-promise-router' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/babel.test' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/commonjs.test' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/express-promise-router.route.test' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/express-promise-router.test' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/test-resources/babel-base-case' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/test-resources/commonjs-base-case' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/tracing.test' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/typescript.test' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/util/http-utils' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/util/launch-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-promise-router/lib/express-promise-router.js' {
  declare module.exports: $Exports<'express-promise-router/lib/express-promise-router'>;
}
declare module 'express-promise-router/test/babel.test.js' {
  declare module.exports: $Exports<'express-promise-router/test/babel.test'>;
}
declare module 'express-promise-router/test/commonjs.test.js' {
  declare module.exports: $Exports<'express-promise-router/test/commonjs.test'>;
}
declare module 'express-promise-router/test/express-promise-router.route.test.js' {
  declare module.exports: $Exports<'express-promise-router/test/express-promise-router.route.test'>;
}
declare module 'express-promise-router/test/express-promise-router.test.js' {
  declare module.exports: $Exports<'express-promise-router/test/express-promise-router.test'>;
}
declare module 'express-promise-router/test/test-resources/babel-base-case.js' {
  declare module.exports: $Exports<'express-promise-router/test/test-resources/babel-base-case'>;
}
declare module 'express-promise-router/test/test-resources/commonjs-base-case.js' {
  declare module.exports: $Exports<'express-promise-router/test/test-resources/commonjs-base-case'>;
}
declare module 'express-promise-router/test/tracing.test.js' {
  declare module.exports: $Exports<'express-promise-router/test/tracing.test'>;
}
declare module 'express-promise-router/test/typescript.test.js' {
  declare module.exports: $Exports<'express-promise-router/test/typescript.test'>;
}
declare module 'express-promise-router/test/util/http-utils.js' {
  declare module.exports: $Exports<'express-promise-router/test/util/http-utils'>;
}
declare module 'express-promise-router/test/util/launch-utils.js' {
  declare module.exports: $Exports<'express-promise-router/test/util/launch-utils'>;
}
