// flow-typed signature: 8262ec5fed32ca22321074e02492fffc
// flow-typed version: <<STUB>>/ignore-loader_v^0.1.2/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignore-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignore-loader' {
  declare module.exports: any;
}
