// flow-typed signature: 753844dc0cae11c06deceb263eadbff8
// flow-typed version: <<STUB>>/nodemon_v^1.18.3/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodemon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodemon' {
  declare module.exports: any;
}
