// flow-typed signature: a00d53b91aed08500bee19ed2bd9132a
// flow-typed version: <<STUB>>/prettier_v^2.3.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}
