// flow-typed signature: a2e5fcba62c7fb6cd7ca524a7a16a950
// flow-typed version: <<STUB>>/webpack-cli_v^4.7.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cli' {
  declare module.exports: any;
}
