// flow-typed signature: 944d3a35b5e28766c121c022163657d1
// flow-typed version: <<STUB>>/webpack-merge_v^5.7.3/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-merge' {
  declare module.exports: any;
}
