// flow-typed signature: 398a850ef6d730db2ede32ab71a4c1b3
// flow-typed version: <<STUB>>/@babel/cli_v^7.0.0-rc.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/cli' {
  declare module.exports: any;
}
