// flow-typed signature: f3b3458cd6e59a4a98cfdce243541705
// flow-typed version: <<STUB>>/@babel/core_v^7.0.0-rc.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/core' {
  declare module.exports: any;
}
