// flow-typed signature: 234cfc66295ad816600cc5b07efaaa74
// flow-typed version: <<STUB>>/@babel/node_v^7.0.0-rc.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/node' {
  declare module.exports: any;
}
