// flow-typed signature: 168a6c4980a9b0a7b70871e972ece367
// flow-typed version: <<STUB>>/@babel/preset-env_v^7.0.0-rc.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-env' {
  declare module.exports: any;
}
