// flow-typed signature: ba2c30cce1686f492628f497e5876f15
// flow-typed version: <<STUB>>/@babel/preset-flow_v^7.13.13/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-flow' {
  declare module.exports: any;
}
