services:
  Controllers.status.get:
    class: ../../src/controllers/StatusGetController.js
    tags:
      - { name: route, attributes: {method: 'GET', path: '/status'} }
  Controllers.root.home:
    class: ../../src/controllers/HomeGetController.js
    tags:
      - { name: route, attributes: {method: 'GET', path: '/'} }
  Controllers.counter.get:
    class: ../../src/controllers/CounterGetController.js
    arguments: ["@Shared.QueryBus"]
    tags:
      - { name: route, attributes: {method: 'GET', path: '/counter'} }
