imports:
  - { resource: ./shared.yaml }
  - { resource: ../routes/routes.yaml }
  - { resource: ./ArticlesCounter/application.yaml }
#  - { resource: ./Courses/application.yaml }
#  - { resource: ./Notifications/application.yaml }
#  - { resource: ./Shared/application.yaml }
