services:
  Shared.QueryBus:
    class: ../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: [ '@Shared.QueryHandlersInformation' ]

  Shared.QueryHandlersInformation:
    class: ../../Contexts/Shared/infrastructure/QueryBus/QueryHandlersInformation
    arguments: ['!tagged queryHandler']

  Shared.PostgresConfig:
    factory:
      class: ../../Contexts/PricesStats/Shared/infrastructure/persistence/postgresql/PostgresqlConfigFactory
      method: 'createConfig'

  Shared.DBConnectionManager:
    factory:
      class: ../../Contexts/Shared/infrastructure/persistence/postgresql/PostgresqlClientFactory
      method: 'createClient'
    arguments: ['prices-stats-backend', '@Shared.PostgresConfig']

  Shared.DomainEventMapping:
    class: ../../Contexts/Shared/infrastructure/EventBus/RabbitMq/DomainEventMapping
    arguments: ['!tagged domainEventSubscriber']

  Shared.DomainEventJsonDeserializer:
    class: ../../Contexts/Shared/infrastructure/EventBus/RabbitMq/DomainEventJsonDeserializer
    arguments: ['@Shared.DomainEventMapping']

  Shared.EventBus:
    synthetic: true
#    class: ../../Contexts/Shared/infrastructure/EventBus/RabbitMq/RabbitMqEventBus
#    arguments: ['@PricesStats.articlesCounter.RabbitMqConfig', '@Shared.DomainEventJsonDeserializer']
