services:
  Backoffice.articles.ArticleCreator:
    class: ../../../Contexts/Backoffice/Articles/application/BackofficeArticleCreator
    arguments: ["@Backoffice.articles.BackofficeArticlesRepository", "@Shared.EventBus"]
  Backoffice.articles.BackofficeArticlesRepository:
    class: ../../../Contexts/Backoffice/Articles/infrastructure/persistence/postgresql/PostgresqlBackofficeArticlesRepository
    arguments: [ "@Shared.DBConnectionManager" ]
  Backoffice.articles.ArticleCreator.Handler:
    class: ../../../Contexts/Backoffice/Articles/application/CreateBackofficeArticleCommandHandler
    arguments: [ "@Backoffice.articles.ArticleCreator" ]
    tags:
      - { name: 'commandHandler' }
  Backoffice.articles.RabbitMqConfig:
    factory:
      class: ../../../Contexts/Backoffice/Articles/infrastructure/EventBus/RabbitMq/RabbitMqConfigFactory
      method: 'createConfig'



