services:
  PricesStats.articlesCounter.ArticlesCounterFinder:
    class: ../../../Contexts/PricesStats/ArticlesCounter/application/Find/ArticlesCounterFinder
    arguments: ["@PricesStats.articlesCounter.ArticlesCounterRepository"]
  PricesStats.articlesCounter.FindArticlesCounterQueryHandler:
    class: ../../../Contexts/PricesStats/ArticlesCounter/application/Find/FindArticlesCounterQueryHandler
    arguments: [ "@PricesStats.articlesCounter.ArticlesCounterFinder" ]
    tags:
      - { name: 'queryHandler' }
  PricesStats.articlesCounter.ArticlesCounterRepository:
    class: ../../../Contexts/PricesStats/ArticlesCounter/infrastructure/persistence/postgresql/PostgresqlArticlesCounterRepository
    arguments: ["@Shared.DBConnectionManager"]

  PricesStats.articlesCounter.RabbitMqConfig:
    factory:
      class: ../../../Contexts/PricesStats/ArticlesCounter/infrastructure/EventBus/RabbitMq/RabbitMqConfigFactory
      method: 'createConfig'

  PriceStats.articleCounter.ArticlesCounterIncrementer:
    class: ../../../Contexts/PricesStats/ArticlesCounter/application/IncrementCounter/ArticlesCounterIncrementer
    arguments: ['@PricesStats.articlesCounter.ArticlesCounterRepository', '@Shared.EventBus']

  PricesStats.articlesCounter.IncrementCounterOnArticleAdded:
    class: ../../../Contexts/PricesStats/ArticlesCounter/application/IncrementCounter/IncrementCounterOnArticleAdded
    arguments: ['@PriceStats.articleCounter.ArticlesCounterIncrementer']
    tags:
      - { name: 'domainEventSubscriber' }


