// flow-typed signature: 5b1eed0a1daf4dbff9ea0f679c6d230b
// flow-typed version: <<STUB>>/spdy_v4.0.2/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spdy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "spdy" {
  declare var agent: typeof npm$namespace$agent;

  declare var npm$namespace$agent: {|
    create: typeof agent$create,
    AgentOptions: Class<agent$AgentOptions>,
    Agent: typeof agent$Agent,
    PlainAgent: typeof agent$PlainAgent,
  |};
  declare class agent$Agent mixins https.Agent {}

  declare class agent$PlainAgent mixins http.Agent {}

  declare function agent$create(
    base: any,
    options: agent$AgentOptions
  ): agent$Agent | agent$PlainAgent;

  declare type agent$AgentOptions = {
    port?: number,
    spdy?: {
      plain?: boolean,
      ssl?: boolean,
      "x-forwarded-for"?: string,
      protocol?: string,
      protocols?: string[],
      ...
    },
    ...
  } & https.AgentOptions;
  declare export interface Handle {
    create(
      options: { [key: string]: any },
      stream: any,
      socket: socket$Socket
    ): Handle;
    getStream(callback?: (stream: any) => void): any;
    assignSocket(socket: socket$Socket, options: { [key: string]: any }): void;
    assignClientRequest(req: any): void;
    assignRequest(req: any): void;
    assignResponse(res: any): void;
    emitRequest(): void;
    emitResponse(status: any, headers: any): void;
  }
  declare var request: typeof npm$namespace$request;

  declare var npm$namespace$request: {|
    onNewListener: typeof request$onNewListener,
  |};
  declare function request$onNewListener(type: string): void;
  declare var response: typeof npm$namespace$response;

  declare var npm$namespace$response: {|
    writeHead: typeof response$writeHead,
    end: typeof response$end,
  |};
  declare function response$writeHead(
    statusCode: number,
    reason: string,
    obj: { [key: string]: any }
  ): void;

  declare function response$writeHead(
    statusCode: number,
    obj: { [key: string]: any }
  ): void;

  declare function response$end(
    data: any,
    encoding: string,
    callback: () => void
  ): void;
  declare var server: typeof npm$namespace$server;

  declare var npm$namespace$server: {|
    create: typeof server$create,
    ServerResponse: Class<server$ServerResponse>,
    PushOptions: Class<server$PushOptions>,
    ServerOptions: Class<server$ServerOptions>,
  |};
  declare type server$Server = https.Server;

  declare type server$PlainServer = http.Server;

  declare type server$IncomingMessage = http.IncomingMessage;

  declare type server$ServerResponse = {
    push(filename: string, options: server$PushOptions): any,
    ...
  } & http.ServerResponse;

  declare function server$create(
    base: any,
    options: https.ServerOptions,
    handler: (
      request: server$IncomingMessage,
      response: server$ServerResponse | http.ServerResponse
    ) => void
  ): server$Server;

  declare function server$create(
    options: https.ServerOptions,
    handler: (
      request: server$IncomingMessage,
      response: http.ServerResponse
    ) => void
  ): server$Server;

  declare function server$create(
    handler: (
      request: server$IncomingMessage,
      response: server$ServerResponse | http.ServerResponse
    ) => void
  ): server$Server;

  declare type server$Protocol =
    | "h2"
    | "spdy/3.1"
    | "spdy/3"
    | "spdy/2"
    | "http/1.1"
    | "http/1.0";

  declare interface server$PushOptions {
    status?: number;
    method?: string;
    request?: any;
    response?: any;
  }

  declare type server$ServerOptions = {
    spdy?: {
      protocols?: server$Protocol[],
      plain?: boolean,
      "x-forwarded-for"?: boolean,
      connection?: {
        windowSize?: number,
        autoSpdy31?: boolean,
        ...
      },
      ...
    },
    ...
  } & https.ServerOptions;
  declare var socket: typeof npm$namespace$socket;

  declare var npm$namespace$socket: {|
    Socket: Class<socket$Socket>,
  |};
  declare interface socket$Socket {}
  declare export type Agent = agent$Agent;
  declare export type PlainAgent = agent$PlainAgent;
  declare export type AgentOptions = agent$AgentOptions;
  declare export type Socket = socket$Socket;
  declare export type Server = server$Server;
  declare export type IncomingMessage = server$IncomingMessage;
  declare export type ServerRequest = server$IncomingMessage;
  declare export type ServerResponse = server$ServerResponse;
  declare export type PlainServer = server$PlainServer;
  declare export type ServerOptions = server$ServerOptions;
  declare export function createAgent(
    base: any,
    options: agent$AgentOptions
  ): agent$Agent | agent$PlainAgent;
  declare export function createAgent(
    options: agent$AgentOptions
  ): agent$Agent | agent$PlainAgent;
  declare export function createServer(
    base: any,
    options: server$ServerOptions,
    handler: (
      request: server$IncomingMessage,
      response: http.ServerResponse
    ) => void
  ): server$Server;
  declare export function createServer(
    options: server$ServerOptions,
    handler: (
      request: server$IncomingMessage,
      response: http.ServerResponse
    ) => void
  ): server$Server;
  declare export function createServer(
    handler: (
      request: server$IncomingMessage,
      response: http.ServerResponse
    ) => void
  ): server$Server;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "spdy/lib/spdy" {
  declare module.exports: any;
}

declare module "spdy/lib/spdy/agent" {
  declare module.exports: any;
}

declare module "spdy/lib/spdy/handle" {
  declare module.exports: any;
}

declare module "spdy/lib/spdy/request" {
  declare module.exports: any;
}

declare module "spdy/lib/spdy/response" {
  declare module.exports: any;
}

declare module "spdy/lib/spdy/server" {
  declare module.exports: any;
}

declare module "spdy/lib/spdy/socket" {
  declare module.exports: any;
}

declare module "spdy/test/client-test" {
  declare module.exports: any;
}

declare module "spdy/test/fixtures" {
  declare module.exports: any;
}

declare module "spdy/test/server-test" {
  declare module.exports: any;
}

// Filename aliases
declare module "spdy/lib/spdy.js" {
  declare module.exports: $Exports<"spdy/lib/spdy">;
}
declare module "spdy/lib/spdy/agent.js" {
  declare module.exports: $Exports<"spdy/lib/spdy/agent">;
}
declare module "spdy/lib/spdy/handle.js" {
  declare module.exports: $Exports<"spdy/lib/spdy/handle">;
}
declare module "spdy/lib/spdy/request.js" {
  declare module.exports: $Exports<"spdy/lib/spdy/request">;
}
declare module "spdy/lib/spdy/response.js" {
  declare module.exports: $Exports<"spdy/lib/spdy/response">;
}
declare module "spdy/lib/spdy/server.js" {
  declare module.exports: $Exports<"spdy/lib/spdy/server">;
}
declare module "spdy/lib/spdy/socket.js" {
  declare module.exports: $Exports<"spdy/lib/spdy/socket">;
}
declare module "spdy/test/client-test.js" {
  declare module.exports: $Exports<"spdy/test/client-test">;
}
declare module "spdy/test/fixtures.js" {
  declare module.exports: $Exports<"spdy/test/fixtures">;
}
declare module "spdy/test/server-test.js" {
  declare module.exports: $Exports<"spdy/test/server-test">;
}
